# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(400, 339)
        self.gridLayout = QtWidgets.QGridLayout(PreferencesDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(PreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(PreferencesDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.settings)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.vggBrowseButton = QtWidgets.QPushButton(self.settings)
        self.vggBrowseButton.setObjectName("vggBrowseButton")
        self.gridLayout_3.addWidget(self.vggBrowseButton, 1, 2, 1, 1)
        self.outputFolderBrowseButton = QtWidgets.QPushButton(self.settings)
        self.outputFolderBrowseButton.setObjectName("outputFolderBrowseButton")
        self.gridLayout_3.addWidget(self.outputFolderBrowseButton, 0, 2, 1, 1)
        self.vggInput = QtWidgets.QLineEdit(self.settings)
        self.vggInput.setObjectName("vggInput")
        self.gridLayout_3.addWidget(self.vggInput, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.settings)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.outputFolderInput = QtWidgets.QLineEdit(self.settings)
        self.outputFolderInput.setObjectName("outputFolderInput")
        self.gridLayout_3.addWidget(self.outputFolderInput, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.settings)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        self.tabWidget.addTab(self.settings, "")
        self.advSettings = QtWidgets.QWidget()
        self.advSettings.setObjectName("advSettings")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.advSettings)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.learningRateInput = QtWidgets.QLineEdit(self.advSettings)
        self.learningRateInput.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.learningRateInput.setObjectName("learningRateInput")
        self.gridLayout_2.addWidget(self.learningRateInput, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.advSettings)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.advSettings)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.advSettings)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.contentWeightInput = QtWidgets.QLineEdit(self.advSettings)
        self.contentWeightInput.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.contentWeightInput.setObjectName("contentWeightInput")
        self.gridLayout_2.addWidget(self.contentWeightInput, 3, 1, 1, 1)
        self.iterationsInput = QtWidgets.QLineEdit(self.advSettings)
        self.iterationsInput.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.iterationsInput.setObjectName("iterationsInput")
        self.gridLayout_2.addWidget(self.iterationsInput, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.advSettings)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.defaultValuesButton = QtWidgets.QToolButton(self.advSettings)
        self.defaultValuesButton.setObjectName("defaultValuesButton")
        self.gridLayout_2.addWidget(self.defaultValuesButton, 8, 1, 1, 1)
        self.temporalWeightInput = QtWidgets.QLineEdit(self.advSettings)
        self.temporalWeightInput.setObjectName("temporalWeightInput")
        self.gridLayout_2.addWidget(self.temporalWeightInput, 6, 1, 1, 1)
        self.tvWeightInput = QtWidgets.QLineEdit(self.advSettings)
        self.tvWeightInput.setObjectName("tvWeightInput")
        self.gridLayout_2.addWidget(self.tvWeightInput, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.advSettings)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.advSettings)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.advSettings)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.advSettings)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.advSettings)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.advSettings)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.advSettings)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 6, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.advSettings)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 2, 1, 1)
        self.styleWeightInput = QtWidgets.QLineEdit(self.advSettings)
        self.styleWeightInput.setObjectName("styleWeightInput")
        self.gridLayout_2.addWidget(self.styleWeightInput, 4, 1, 1, 1)
        self.deepFlowCheckBox = QtWidgets.QCheckBox(self.advSettings)
        self.deepFlowCheckBox.setToolTip("")
        self.deepFlowCheckBox.setObjectName("deepFlowCheckBox")
        self.gridLayout_2.addWidget(self.deepFlowCheckBox, 7, 1, 1, 1)
        self.tabWidget.addTab(self.advSettings, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(PreferencesDialog)
        self.tabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(PreferencesDialog.accept)
        self.buttonBox.rejected.connect(PreferencesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Dialog"))
        self.vggBrowseButton.setText(_translate("PreferencesDialog", "Browse"))
        self.outputFolderBrowseButton.setText(_translate("PreferencesDialog", "Browse"))
        self.label_7.setText(_translate("PreferencesDialog", "Output folder:"))
        self.label_6.setText(_translate("PreferencesDialog", "VGG path:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("PreferencesDialog", "Settings"))
        self.label_14.setText(_translate("PreferencesDialog", "Temporal Wieght:"))
        self.label_5.setText(_translate("PreferencesDialog", "TV Viewght:"))
        self.label.setText(_translate("PreferencesDialog", "Content Weight:"))
        self.label_2.setText(_translate("PreferencesDialog", "Learning Rate:"))
        self.defaultValuesButton.setText(_translate("PreferencesDialog", "Use default values"))
        self.label_3.setText(_translate("PreferencesDialog", "Iterations per Frame:"))
        self.label_4.setText(_translate("PreferencesDialog", "Style Weight:"))
        self.label_11.setText(_translate("PreferencesDialog", "[float]"))
        self.label_8.setText(_translate("PreferencesDialog", "[float]"))
        self.label_10.setText(_translate("PreferencesDialog", "[float]"))
        self.label_9.setText(_translate("PreferencesDialog", "[int]"))
        self.label_13.setText(_translate("PreferencesDialog", "[float]"))
        self.label_12.setText(_translate("PreferencesDialog", "[float]"))
        self.deepFlowCheckBox.setText(_translate("PreferencesDialog", "Use deep flow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.advSettings), _translate("PreferencesDialog", "Advanced Settings"))

